name: TeamManager
main: com.xhizors.TeamManager.TeamManager
version: 1.0
description: >
             Team Manager
commands:
  friendlyfiretoggle:
    description: Toggle Wordfiter
    permission: teammanager.friendlyfiretoggle
    permission: /friendlyfiretoggle